# Generated by Django 3.2.9 on 2021-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myweb_main', '0009_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('posts', models.ManyToManyField(related_name='tags', to='myweb_main.Post')),
            ],
        ),
    ]
