# Generated by Django 3.2.9 on 2021-12-25 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('like_comment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecomment',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes_comment', to='comment_app.comment'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='likecomment',
            unique_together={('user', 'comment')},
        ),
        migrations.RemoveField(
            model_name='likecomment',
            name='post',
        ),
    ]
