# Generated by Django 3.2.9 on 2021-12-25 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('like_tag_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liketeg',
            name='tag',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='likes_teg', to='tags_app.tag'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='liketeg',
            unique_together={('user', 'tag')},
        ),
        migrations.RemoveField(
            model_name='liketeg',
            name='post',
        ),
    ]
