# Generated by Django 3.2.9 on 2021-12-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
